### ISSUE TITLE
Before making public (v0.1?)

### ISSUE THREAD

**Issue by dvdkouril** [dvdkouril/chromospace#5]
Features:
- [x] Ways to define coloring of the 3D structures (#4)
- [x] Basic selections API (#3)
- [ ] ~~Selecting in 3D~~
- [x] on hover tooltip (kinda done in #25) 
- [x] #49 

Repository setup:
- [x] CI: tests, ...? (Done in #9, #10, #11, #13)

Not a priority (or not longer doing in chromospace):
- Grammar API -> chromospace will serve the 3D parts of Gosling grammar
- linking genomic signals (1D data) to properties of visual marks (#20) -> will be a use case in Gosling, but not directly supported by chromospace (we do not want to duplicate functionality around loading all the genomic file formats in chromospace)
